config/routes.rb
Maia::Engine.routes.draw do
  post 'messages/push', to: 'messages#push', as: :push
  root to: 'messages#new'
end

app/models/concerns/maia/model.rb
module Maia
  module Model
    extend ActiveSupport::Concern

    included do
      has_many :devices, class_name: 'Maia::Device', as: :pushable
    end
  end
end

app/models/maia/application_record.rb
module Maia
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/maia/device.rb
module Maia
  class Device < ApplicationRecord
    belongs_to :pushable, polymorphic: true

    validates :token, presence: true, uniqueness: { scope: :pushable }
    validates :platform, inclusion: { in: %w(ios android) }, allow_nil: true

    before_save :reset_token_expiry

    def reset_token_expiry
      self.token_expires_at = Time.current + expire_token_in
    end

    def expire_token_in
      14.days
    end

    def token_expired?
      token_expires_at.nil? || token_expires_at.past?
    end

    def self.owned_by(pushable)
      where(pushable: pushable).distinct
    end

    def self.tokens
      pluck(:token)
    end

    def self.ios
      where platform: 'ios'
    end

    def self.android
      where platform: 'android'
    end

    def self.unknown
      where platform: nil
    end
  end
end

app/controllers/concerns/maia/controller.rb
module Maia
  module Controller
    extend ActiveSupport::Concern

    def create
      if device_exists?
        @device = find_device
        update_device @device
      else
        @device = create_device_token
      end
      respond_with @device
    end

    def destroy
      @device = find_device params[:id]
      @device.destroy
      respond_with @device
    end

    private
      def device_exists?(token = params[:device][:token])
        current_user.devices.exists? token: token
      end

      def find_device(token = params[:device][:token])
        current_user.devices.find_by! token: token
      end

      def update_device(device)
        device.attributes = permitted_params
        device.reset_token_expiry
        device.save
      end

      def create_device_token
        current_user.devices.create permitted_params
      end

      def permitted_params
        params.require(:device).permit :token, :platform
      end
  end
end

app/views/layouts/maia/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maia Test Console</title>
  <%= stylesheet_link_tag    "//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= javascript_include_tag "//code.jquery.com/jquery-2.1.3.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/maia/messages/new.html.erb
<div class="container">
  <% flash.each do |k, v| %>
    <% klass = { notice: 'success', alert: 'danger' }.fetch(k.intern, 'info') %>
    <div class="alert alert-<%= klass %>" role="alert"><%= v %></div>
  <% end %>
  <%= form_for @push, url: push_path, html: { class: 'console form col-md-6 col-md-offset-3' } do |f| %>
    <div class="form-group">
      <%= f.label :device_token %>
      <%= f.text_field :device_token, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :klass, 'Message' %>
      <%= f.select :klass, ['', @klasses].flatten, {}, class: 'form-control' %>
    </div>
    <% @stubs.each do |stub| %>
      <div class="form-group hide" data-klass="<%= stub.klass %>">
        <%= f.label :data %>
        <% stub.fields.each do |field, type| %>
          <%= text_field_tag "console_push[#{stub.klass}][data][#{field}][value]", nil, placeholder: field, class: 'form-control' %>
          <%= hidden_field_tag "console_push[#{stub.klass}][data][#{field}][type]", type.to_s %>
        <% end %>
      </div>
    <% end %>
    <%= f.submit 'Push', class: 'btn btn-primary' %>
  <% end %>
</div>